name = "didicameras-r2-worker"
main = "src/index.js"
compatibility_date = "2025-06-15"

account_id = "your_cloudflare_account_id"
workers_dev = true
route = ""

# Bindings for R2 or secrets go here
[env.production]
account_id = "your_cloudflare_account_id"
route = "didicameras.live/recordings/*"

[vars]
MY_ENV_VAR = "value"

[vars.SECRET_API_KEY]
# You can also set secrets via `wrangler secret put SECRET_API_KEY`
