# Generated by Django 5.2.1 on 2025-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_recording_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
