# Generated by Django 5.2.1 on 2025-06-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_camera_stream_url_delete_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='app.camera')),
            ],
        ),
    ]
