# Generated by Django 5.2.1 on 2025-06-16 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ffmpegconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffmpegconfig',
            options={'verbose_name': 'FFmpeg Config', 'verbose_name_plural': 'FFmpeg Configs'},
        ),
        migrations.AddField(
            model_name='ffmpegconfig',
            name='recording_bitrate',
            field=models.PositiveSmallIntegerField(default=28, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='ffmpegconfig',
            name='recording_format',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='ffmpegconfig',
            name='recording_resolution',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
