# Generated by Django 5.2.1 on 2025-06-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ffmpegconfig_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ffmpegconfig',
            old_name='recording_bitrate',
            new_name='recording_crf',
        ),
        migrations.AddField(
            model_name='ffmpegconfig',
            name='recording_preset',
            field=models.CharField(default='veryfast', max_length=12),
        ),
    ]
