# Generated by Django 5.2.1 on 2025-06-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_recording_bitrate_ffmpegconfig_recording_crf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
    ]
