# Generated by Django 5.2.1 on 2025-06-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_camera_location_remove_camera_stream_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
