# Generated by Django 5.2.1 on 2025-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_camera_location_remove_camera_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='live_url',
            field=models.URLField(default=''),
        ),
    ]
