# Generated by Django 5.2.1 on 2025-06-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_camera_live_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
