# Generated by Django 5.2.1 on 2025-06-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_camera_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
    ]
